trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Fortify
  jobs:
  - job: FortifySAST
    displayName: Fortify SAST
    steps:
    - task: FortifyScanCentralSAST@7
      inputs:
        scanCentralCtrlUrl: 'http://3.75.227.95:8080/scancentral-ctrl/'
        scanCentralClientToken: '$(ScanCentral.ClientToken)'
        sscUrl: 'http://3.75.227.95:2210/ssc'
        sscCiToken: '$(ScanCentral.SscCiToken)'
        uploadToSSC: true
        applicationIdentifierType: 'byId'
        applicationVersionId: '21'
        #buildFailureCriteria: '[fortify priority order]:critical'
        #taskResultForBuildFailureCriteria: 'WARN'
        block: true
        outputFile: 'result.fpr'
        logFile: 'fortify.log'
        buildTool: 'mvn'