trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Fortify
  jobs:
  - job: FortifySAST
    displayName: Fortify SAST
    steps:
    - task: FortifyScanCentralSAST@7
      inputs:
        scanCentralCtrlUrl: 'http://35.158.210.68:8080/scancentral-ctrl/'
        scanCentralClientToken: '$(ScanCentral.ClientToken)'
        sscUrl: 'http://35.158.210.68:2210/ssc'
        sscCiToken: '$(ScanCentral.SscCiToken)'
        uploadToSSC: true
        applicationIdentifierType: 'byId'
        applicationVersionId: '21'
        buildFailureCriteria: '[fortify priority order]:critical'
        taskResultForBuildFailureCriteria: 'WARN'
        buildTool: 'mvn'