trigger: none
#- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Fortify
  jobs:
  - job: FortifySAST
    displayName: Fortify SAST
    steps:
    - task: FortifyScanCentralSAST@7
      inputs:
        scanCentralCtrlUrl: 'http://3.123.38.205:8080/scancentral-ctrl/'
        scanCentralClientToken: '$(ScanCentral.ClientToken)'
        sscUrl: 'http://3.70.95.75:2210/ssc'
        sscCiToken: '$(ScanCentral.SscCiToken)'
        uploadToSSC: true
        applicationIdentifierType: 'byId'
        applicationVersionId: '7'
        buildFailureCriteria: '[fortify priority order]:critical'
        taskResultForBuildFailureCriteria: 'WARN'
        buildTool: 'mvn'
        block: true
        outputFile: 'result.fpr'
        logFile: 'scan.log'
        overwrite: true
    - task: CmdLine@2
      inputs:
        script: 'FPRUtility -information -categoryIssueCounts -project C:\dev\agent\_work\2\s\result.fpr'

- stage: Debricked
  jobs:
  - job: Debricked
    displayName: Fortify SCA (Debricked)
    steps:
      - script: mvn dependency:tree -DoutputFile=.debricked-maven-dependencies.tgf -DoutputType=tgf
        displayName: 'mvn dependency:tree'
      - script: |
          env > env.list
          docker run -v $HOME:$HOME --env-file ./env.list --entrypoint "/azure-devops.sh" debricked/debricked-scan:latest
        displayName: 'Debricked scan'
        env:
          DEBRICKED_TOKEN: $(DEBRICKED_TOKEN)