# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Fortify'
  jobs:
  - job: FortifySAST
    steps:
    - task: FortifyScanCentralSAST@7
      inputs:
        scanCentralCtrlUrl: 'http://3.123.38.205:8080/scancentral-ctrl/'
        scanCentralClientToken: '$(ScanCentral.ClientToken)'
        sscUrl: 'http://3.70.95.75:2210/ssc'
        sscCiToken: '$(ScanCentral.SscCiToken)'
        uploadToSSC: true
        applicationIdentifierType: 'byId'
        applicationVersionId: '7'
        buildFailureCriteria: '[fortify priority order]:critical'
        buildTool: 'mvn'

  - job: debricked
    displayName: Debricked scan
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: mvn dependency:tree -DoutputFile=.debricked-maven-dependencies.tgf -DoutputType=tgf
        displayName: 'mvn dependency:tree'
      - script: |
          env > env.list
          docker run -v $HOME:$HOME --env-file ./env.list --entrypoint "/azure-devops.sh" debricked/debricked-scan:latest
        displayName: 'Debricked scan'
        env:
          DEBRICKED_TOKEN: $(DEBRICKED_TOKEN)